parameters:
     db.host: mysql:host=localhost
     db.name: dbname=bd_gsb
     db.user: root
     db.mdp:  root

services:
#    slamgsb.example:
#        class: SLAM\GSBBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     slamgsb.pdo:
         class: SLAM\GSBBundle\services\PdoGsb
         arguments: ["mysql:host=localhost", "dbname=bd_gsb", "root","root"]
